episodeLength: 25
compass: false
weather: false
witch : false
potion2 : false
daylightCycle:
    do: false
    time: 6000
allow-reconnect: false
scoreboard: Kill the Bite
kick-on-death:
    kick: true
    time: 30
update-checker: true