name: UHPlugin
main: me.azenet.UHPlugin.UHPlugin
version: 0.1

commands:
   uh:
      description: Ultra Hardcore
      usage: /uh <subcommand>
   life:
      description: Ultra Hardcore Life
      usage: /uh <subcommand>
   cast:
      description: Ultra Hardcore Cast
      usage: /uh <subcommand>
   head:
      description: Ultra Hardcore Head Giver
      usage: /uh <subcommand>